### ISSUE TITLE
Cannot build junixsocket on aarch64 Linux (currently unsupported)

### ISSUE THREAD

**Issue by netcom-rs** [kohlschutter/junixsocket#102]
hi all.

Ubuntu 20.04, clang10, openjdk8, arm64 architecture

when running `mvn clean install` i get the following:

`[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/accept.d11dea3b.nodeps.o: No such file or directory
[INFO] ------------------------------------------------------------------------
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/address.4fb4b6b.nodeps.o: No such file or directory
[INFO] BUILD FAILURE
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/ancillary.6880d22c.nodeps.o: No such file or directory
[INFO] ------------------------------------------------------------------------
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/bind.67c497b0.nodeps.o: No such file or directory
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/capabilities.d8a0eae9.nodeps.o: No such file or directory
[INFO] Total time:  12.503 s
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/config.2e7b11f5.nodeps.o: No such file or directory
[INFO] Finished at: 2022-03-20T15:26:24Z
[INFO] ------------------------------------------------------------------------
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/connect.ae54c2e1.nodeps.o: No such file or directory
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/credentials.4a241f73.nodeps.o: No such file or directory
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.10.1:nar-compile (default-nar-compile) on project junixsocket-native: NAR: Compile failed: /home/ubuntu/installer-build/junixsocket/junixsocket-native/crossclang/bin/gcc failed with return code 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/exceptions.9a6c5137.nodeps.o: No such file or directory
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/filedescriptors.a633805f.nodeps.o: No such file or directory
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/init.73faefc3.nodeps.o: No such file or directory
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/jniutil.589b5fde.nodeps.o: No such file or directory
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/listen.a14c0f3a.nodeps.o: No such file or directory
[ERROR] OUTPUT>gcc: error: /home/ubuntu/installer-build/junixsocket/junixsocket-native/target/nar/obj/aarch64-Linux-clang/pipe.7fa95ce1.nodeps.o: No such file or directory`

I think it has to do something with makefile.

Best regards,
Aleksa.

**Comment by sriemer** [comment]
The `aarch64` support is produced via `LLVM`/`clang` cross compilation for Linux. It is expected that the native build is done on an x86_64 Linux machine for now.
For MacOS 11, the aarch64 native support has been added via commit https://github.com/kohlschutter/junixsocket/commit/810529af1f6ec8281c4bcb7dc950f8a665e0889f. There you can see the files that have to be extended for your feature request.

**Comment by kohlschuetter** [comment]
Closing resolved ticket due to inactivity. Please re-open if you find any problems. Thanks for reporting!
