### ISSUE TITLE
Support on WindowsServer

### ISSUE THREAD

**Issue by sake92** [kohlschutter/junixsocket#104]
**Describe the bug**
Could not load native library junixsocket-native for architecture amd64-WindowsServer2022

**To Reproduce**
1. make a Github Action
2. use windows-latest or windows-2022, I suppose it is similar to lower versions, see https://github.com/actions/virtual-environments
3. run an app using junixsocket

**Expected behavior**
Sockets work

**Output/Screenshots**
https://github.com/com-lihaoyi/mill/pull/1852#issuecomment-1114332274

**Environment (please complete the following information):**
 - OS: WindowsServer2022
 - windows 10
 - Version 10.0.20348 Build 643

**Notes**
We found a workaround by manually setting `System.setProperty("os.name", "Windows10")`

**Comment by kohlschuetter** [comment]
This should be fixed in commit 2f8f096b84fba1ae26058d41cc03df47719379df. Thank you for reporting!

**Comment by sake92** [comment]
@kohlschuetter thank you for fixing this!  
It works fine now. 🎉  
https://github.com/com-lihaoyi/mill/pull/1894
