### ISSUE TITLE
Failure to load DLL on Windows11

### ISSUE THREAD

**Issue by jvanzyl** [kohlschutter/junixsocket#106]
It appears that the amd64-Windows10 DLL is packaged up in the JAR, and I assume it's compatible with Windows11, but on Windows11 it's specifically looking for `amd64-Windows11`:

`java.lang.UnsatisfiedLinkError: Could not load native library junixsocket-native for architecture amd64-Windows11`

Would a type of link work on Windows? Or a copy of the DLL named for Windows11?

**Comment by kohlschuetter** [comment]
This should be fixed in version 2.5.0 / commit 2f8f096b84fba1ae26058d41cc03df47719379df. Thank you for reporting!

**Comment by jvanzyl** [comment]
Thanks @kohlschuetter ! I'll give it a try!

**Comment by kohlschuetter** [comment]
@jvanzyl Assuming this is working for you now. Please reopen if you encounter any issues with version 2.5.0 or newer. Thanks again for reporting!
