### ISSUE TITLE
Server error "too many files open"

### ISSUE THREAD

**Issue by 2296894808** [kohlschutter/junixsocket#107]
**Describe the bug**
The server side reports ”too many files open“ error

**To Reproduce**
1. Write UDS server
2. The client sends a request to the server in a loop
3. The server will report an error when it receives enough requests. My mac machine reports an error when it reaches more than 10,000 requests

**Expected behavior**
server has no error

**Output/Screenshots**
![image](https://user-images.githubusercontent.com/75785950/173483601-5eea6dee-8026-4634-9fc2-3e8d68e45d98.png)

**Environment (please complete the following information):**
 - OS: [mac os]
 - Version [11.4]
 - java version "1.8.0_131"
 - junixsocket version 2.4.0

**Notes**
http://t.csdn.cn/mWTRq

**Comment by kohlschuetter** [comment]
Please provide some code to reproduce your issue.
Does this still reproduce with junixsocket 2.5.0?

**Comment by 2296894808** [comment]
Thank you very much for your reply, I tried 2.5.0 and no longer have this problem. I saw in the 2.5.0 version change log that the file descriptor leak problem was fixed. At the same time, I also posted the code I tested to CSDN.
