### ISSUE TITLE
DBeaver support like no.fiken.oss.junixsocket

### ISSUE THREAD

**Issue by TW-Goldencode** [kohlschutter/junixsocket#120]
**Describe the bug**
As mentioned in https://github.com/dbeaver/dbeaver/issues/10701#issuecomment-913148861 , the official `com.kohlschutter.junixsocket` fork of junixsocket is incompatible with DBeaver, while `no.fiken.oss.junixsocket` *is* compatible.
I just checked this with DBeaver `22.2.2` (latest), and I can confirm that's still the case.
`no.fiken.oss.junixsocket` is at version `1.0.2`.

Is this an issue that can be overcome? 
It's not a problem (yet), but I couldn't find evidence if you're even aware of the issue.

The post above mentions (no.fiken compared to com.kohlschutter):
> following the official postgres jdbc documentation

Which sounds suspicious. Do you think the issue is strictly within the DBeaver scope? 
My use case: Now I have internal (DSL client-server) IPC using junixsocket `2.5.2` communication, I'm exploring UDS connections to PostgreSql within our framework as well (it's currently using networking IPC on localhost).
It follows I'll be using the same junixsocket jar for both UDS's.

**Environment:**
 - OS: Linux
 - Distribution: Ubuntu 22.04
 - Version: 2.5.2

**Comment by kohlschuetter** [comment]
`com.kohlschutter.junixsocket` is the official junixsocket, not a fork, still maintained by myself, its original author.

If I remember correctly, that `no.fiken.oss.junixsocket` was forked from junixsocket 1.0 when it was still on Google Code.
A lot of things have changed since then. Specifically, PostgreSQL support has been added and enhanced a while ago, so I think using that fork has no benefits anymore.

See `https://kohlschutter.github.io/junixsocket/dependency.html` for details how to add junixsocket 2.5.2 (and other recent versions) to PostgreSQL.

Are you having problems with using junixsocket 2.5.2 in that environment?

**Comment by TW-Goldencode** [comment]
> `com.kohlschutter.junixsocket` is the official junixsocket, not a fork, still maintained by myself, its original author.

Apologies if my wording was unclear, I am aware of that. 
> Are you having problems with using junixsocket 2.5.2 in that environment?
> 

Yes. 
> If DBeaver has a dependency on an older junixsocket version, you can try excluding that dependency and use a later version instead.

No, that's not the case. 
In DBeaver, you can select your own dependencies per connection. 
No junixsocket is downloaded by default. 
If I pick the no.fiken fork, it works. 
If I replace it by the official junixsocket, 2.5.2, it falls to connect.

**Comment by kohlschuetter** [comment]
I just verified that DBeaver 22.2.2 can connect to PostgreSQL 14.5 with junixsocket 2.5.2:

Server: Connect by: URL
URL: jdbc:postgresql://localhost/postgres

Driver properties:
socketFactory: `org.newsclub.net.unix.AFUNIXSocketFactory$FactoryArg`
socketFactoryArg: `/tmp/.s.PGSQL.5432`
sslmode: `disable`

I added junixsocket via "Edit Driver Settings / Libraries" to the PostgreSQL driver:
I used "Add Artifact". I added the following two artifacts (separately):

```
<dependency>
  <groupId>com.kohlschutter.junixsocket</groupId>
  <artifactId>junixsocket-common</artifactId>
  <version>2.5.2</version>
</dependency>
```
and
```
<dependency>
  <groupId>com.kohlschutter.junixsocket</groupId>
  <artifactId>junixsocket-native-common</artifactId>
  <version>2.5.2</version>
</dependency>
```

I tried
```
<dependency>
  <groupId>com.kohlschutter.junixsocket</groupId>
  <artifactId>junixsocket-core</artifactId>
  <version>2.5.2</version>
  <type>pom</type>
</dependency>
```
but it seems that DBeaver has a problem with POM-only dependencies, complaining about a missing jar file.

Was that maybe the issue?

**Comment by TW-Goldencode** [comment]
That might have been the issue (I thought I checked? - never mind).
Thank you for checking, this post is a good reference for people encountering this.
Closing this issue.

**Comment by kohlschuetter** [comment]
The POM-issue is tracked by DBeaver via https://github.com/dbeaver/dbeaver/issues/13048, however no current milestone is set.
