### ISSUE TITLE
Add support for Android

### ISSUE THREAD

**Issue by shenzhigang** [kohlschutter/junixsocket#123]
**Describe the bug**
Error occurs when start the `nanoHttpdServerDemo`.
`No implementation found for void org.newsclub.net.unix.NativeUnixSocket.initServerImpl` 
Version: 2.6.1
`junixsocket-common-2.6.1`, `junixsocket-native-common-2.6.1`, `junixsocket-server-2.6.1` was imported.

**To Reproduce**
```
try {
    SocketAddress addr = parseAddress(
            new String[]{}, 
            AFUNIXSocketAddress.of(new File("/data/local/tmp/junixsocket-http-server.sock"))
    );
    NanoHttpdServerDemo  nanoHttpdServerDemo = new NanoHttpdServerDemo (addr);
    nanoHttpdServerDemo.start(NanoHTTPD.SOCKET_READ_TIMEOUT, false);
} catch (IOException e) {
    e.printStackTrace();
    Logger.e(e, e.getMessage());
}
```

**Output/Screenshots**
![image](https://user-images.githubusercontent.com/8005935/204715466-65d1d1fc-131c-4114-b34a-a744252e534d.png)

**Environment (please complete the following information):**
 - OS: [Android]
 - Version [10.0]

**Comment by kohlschuetter** [comment]
Thanks for reporting!

I haven't really looked much into supporting Android yet. By the looks of the screenshot, I think junixsocket can't find or can't load the native library. 

Can you please provide an Android project setup that exposes this bug? This would speed up debugging.

**Comment by shenzhigang** [comment]
Here is a sample android project that exposes this bug.
[JunixsocketAndroidSample.zip](https://github.com/kohlschutter/junixsocket/files/10150195/JunixsocketAndroidSample.zip)

In addition, I tried to manually load `libjunixsocket-national-2.6.1. so`, and it says that `libc` cannot be found. It may be necessary to separately compile native library for Android.

**Comment by kohlschuetter** [comment]
Thanks! 

I'm having some beginner's problems with Android Studio (I'm getting "INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113'" with this project, which probably just means that my IDE/device setup is somewhat wrong. (I don't have much experience with Android Studio).

> In addition, I tried to manually load libjunixsocket-national-2.6.1. so, and it says that libc cannot be found. It may be necessary to separately compile native library for Android.

Try the `-nodeps` library variant, which should not depend on libc. If that doesn't work, then you may have to compile the native library part (junixsocket-native/src/...) against whatever libc equivalent Android provides.

**Comment by kohlschuetter** [comment]
Heads up: I now can compile and run selftest on an Android emulator. It will take a little longer to get it fully working, but we're getting there...

**Comment by kohlschuetter** [comment]
@shenzhigang The Android integration is getting close to being shippable.

Would you mind testing the following APK? Please unzip first
[junixsocket-selftest-android-2.7.0-SNAPSHOT.apk.zip](https://github.com/kohlschutter/junixsocket/files/11782601/junixsocket-selftest-android-2.7.0-SNAPSHOT.apk.zip)

See `junixsocket-selftest-android` for the source code.

**Comment by kohlschuetter** [comment]
@shenzhigang Could you please verify that it works for you? Thanks for your help!

**Comment by shenzhigang** [comment]
> @shenzhigang Could you please verify that it works for you? Thanks for your help!

Sorry to keep you waiting for so long.
Here is the logs:
[logs.txt](https://github.com/kohlschutter/junixsocket/files/11969597/logs.txt)

**Comment by kohlschuetter** [comment]
@shenzhigang Great, thanks for providing the selftest logs!
Looks like it worked :-)
