### ISSUE TITLE
AFUNIXInput/OuputStream are not close when socket is closed.

### ISSUE THREAD

**Issue by bdaskalov** [kohlschutter/junixsocket#13]
AFUNIXInput/OuputStream keep a reference to the file descriptor even after the socket is closed. This can lead to a really annoying bugs as file descriptor are reused by the process. For example I was closing the input stream after the socket and this created a rece condition which caused an unrelated stream to be spontaneously closed.

**Comment by kohlschuetter** [comment]
This should be fixed in 2.1.1. Please verify. Thanks for reporting!

**Comment by bdaskalov** [comment]
Thanks for fixing this. Unfortunately this was a really long time ago and I don't really remember what I was using this library for.

**Comment by kohlschuetter** [comment]
Haha, neither can't I :-)
