### ISSUE TITLE
Sending large ByteBuffers is broken

### ISSUE THREAD

**Issue by kohlschuetter** [kohlschutter/junixsocket#135]
**Describe the bug**

per @kevink-sq 

we ran into response problems when using the jetty org.newsclub.net.unix.jetty.AFSocketServerConnector in version 2.6.2 in production. We were looking for alternatives to address the jnr-unixsocket load issue and tried junixsocket.

symptoms:

* when the jetty service using the AFSocketServerConnector returned a response greater than 32KB, the same first 32KB (exactly every 0x8000 bytes) was repeated. For example, if the response was 100KB, then the same first 32KB was repeated until 100KB.
* server did not log a warning or error and the request looked like a 200 response on the server side. Only when client attempted to parse the response was there an error (especially if it was supposed to be structured data).
* OS socket SO_SNDBUF was verified to be 212MB.
* Swapping out the connector to Jetty 10's UnixDomainServerConnector fixed the issue (note swapping the connector was the only diff in the server, no other changes/updates were present)

**Comment by kohlschuetter** [comment]
@kevink-sq Please verify that the bug has been fixed with the latest 2.7.0-SNAPSHOT build (or code from main); fixed in commit 3994501

**Comment by kohlschuetter** [comment]
junixsocket 2.7.0 has been released. Please verify with this version, and re-open if necessary. Thanks again for reporting!

**Comment by kevink-sq** [comment]
Thanks for quickly addressing this issue. Will do another production test to verify.

**Comment by kevink-sq** [comment]
Verified the fix during a production load test. Large responses are now being properly returned.

**Comment by kevink-sq** [comment]
Although the large bytebuffer issue was fixed, another issue was found in production and we had to roll back: https://github.com/kohlschutter/junixsocket/issues/138
