### ISSUE TITLE
Does not initialize on busybox

### ISSUE THREAD

**Issue by CodingFabian** [kohlschutter/junixsocket#14]
I try to get an app running which tries to open a socket in a busybox docker container.
I created https://github.com/scijava/native-lib-loader/issues/6 because I was suspecting that the native loader fails to load the lib, however I came to realisation that it could also be that your c code might not work in a busybox linux.
I am willing to help to get this running. Let me know if I can provide data to debug the native call.

**Comment by kohlschuetter** [comment]
Can you please try again with 2.1.1? Thanks for reporting!

**Comment by CodingFabian** [comment]
we gave up on busybox, so I guess we can close this out.
