### ISSUE TITLE
[junixsocket 2.3.2] java.net.SocketException: Cannot find method "setCreated" or field "created" in java.net.Socket. Unsupported JVM?

### ISSUE THREAD

**Issue by freedom1b2830** [kohlschutter/junixsocket#149]
see https://github.com/moaxcp/x11-client/issues/20

junixsocket-selftest-2.8.3 LOG:
```
sha256summ:
f3a23e48d89d0277f5e99c3e9c7a7681d64b91ec33fc7162559f6f5abdb6cdf4 http://ix.io/4LHD
```

**Comment by kohlschuetter** [comment]
@freedom1b2830 That project uses junixsocket 2.3.2, so a very outdated and knowingly buggy version.

**Comment by freedom1b2830** [comment]
yes, the problem was in the old version.
