### ISSUE TITLE
MySQL socket factory: Respect timeouts to prevent indefinite blocking

### ISSUE THREAD

**Issue by x2zh** [kohlschutter/junixsocket#154]
**Describe the bug**
In the org.newsclub.net.mysql.AFUNIXDatabaseSocketFactoryCJ#connect method, the timeout parameter is not set when using the AFUNIXSocket#connectTo method. The default timeout is 0. If there are some abnormalities in the socket, the connectTo operation may be permanently blocked.
```
public <T extends Closeable> T connect(String hostname, int portNumber, PropertySet props, int loginTimeout) throws IOException {
        ..........
        this.rawSocket = AFUNIXSocket.connectTo(new AFUNIXSocketAddress(socketFile));
       ...........
    }
```

**Expected behavior**
Set the timeout correctly to prevent permanent blockage.

**Comment by kohlschuetter** [comment]
Thanks for reporting, @x2zh!

Please verify with the latest code and let me know if that fixes your issue.

**Comment by kohlschuetter** [comment]
2.9.1 has been released, please verify. Thanks again for reporting!
