### ISSUE TITLE
Make it possible to build junixsocket native library without using maven

### ISSUE THREAD

**Issue by quanah** [kohlschutter/junixsocket#16]
There really is no need to download hundreds of packages or to use maven to build the native library.  Please provide an alternative.

**Comment by kohlschuetter** [comment]
Please provide one or more of the following:
1. A pull request with your proposed changes.
2. A constructive question.

**Comment by quanah** [comment]
Yeah, never mind.  I am converting over from junixsocket 1.x, and didn't realize about the change to using NAR.
