### ISSUE TITLE
is unix domain socket abstract namespace supported?

### ISSUE THREAD

**Issue by alexandnpu** [kohlschutter/junixsocket#26]
The abstract namespace requires that the address name starts with a null char.

If this is supported, how to use it in junixsocket.

**Updated:**

After reading your jni code and having done google search, I find that you do not have the support.
The main reason is [this](https://github.com/kohlschutter/junixsocket/blob/master/junixsocket-native/src/main/c/org_newsclub_net_unix_NativeUnixSocket.c#L125)

At this line, you use GetStringUTFChars, which returns a modified utf-8 c string, which is explained quite well in this [SO](http://stackoverflow.com/questions/32205446/getting-true-utf-8-characters-in-java-jni).

So maybe some change should be done your C code to support the abstract namespace in unix domain socket.

**Comment by kohlschuetter** [comment]
Thanks for reporting!

This would be a Linux-specific feature, but certainly worth exploring.
I believe we'd have to change AFUNIXSocketAddress as well, as that currently only takes a File instance.

Pull requests welcome!

**Comment by kohlschuetter** [comment]
Please upgrade your dependencies to junixsocket 2.2.0. We now support the abstract namespace on both Linux and Windows.

**Comment by alexandnpu** [comment]
@kohlschuetter , thanks for your great work! I will give 2.2.0 a try.
