### ISSUE TITLE
Outdated documentation regarding installation of native JNI libraries

### ISSUE THREAD

**Issue by neuhaus** [kohlschutter/junixsocket#30]
I think at some point the project switched over to NAR however the only documentation there is (at https://code.google.com/archive/p/junixsocket/wikis/GettingStarted.wiki) did not get updated.

Is there any documentation that tells me how I can get the native libraries to load with release 2.0.4?
I built the `libjunixsocket-native-2.0.4.so` file but java can't find it.

PS I'm using gradle in my project

**Comment by gesellix** [comment]
I use these dependencies in my Gradle script:

```
    compile('com.kohlschutter.junixsocket:junixsocket-native-common:2.0.4') {
        exclude module: 'log4j'
    }
    compile('com.kohlschutter.junixsocket:junixsocket-common:2.0.4') {
        exclude module: 'log4j'
    }
```

**Comment by neuhaus** [comment]
I was using `compile 'com.kohlschutter.junixsocket:junixsocket-native:2.0.4'` previously, changing it to `junixsocket-native-common` did the trick. Thanks!
