### ISSUE TITLE
IOException instead of SocketTimeoutException raised after timeout

### ISSUE THREAD

**Issue by neuhaus** [kohlschutter/junixsocket#34]
In my code, I set a timeout using the [setSoTimeout](https://docs.oracle.com/javase/8/docs/api/java/net/ServerSocket.html#setSoTimeout-int-)() method of `AFUNIXServerSocket` inherited from `ServerSocket`. 

The documentation for this method states:

> With this option set to a non-zero timeout, a call to accept() for this ServerSocket will block for only this amount of time. If the timeout expires, a **java.net.SocketTimeoutException** is raised, though the ServerSocket is still valid.

However, I am getting an IOException instead when calling `accept()`. An IOException should only be thrown _if an I/O error occurs when waiting for a connection_.

Here is the stacktrace:

```
org.newsclub.net.unix.AFUNIXSocketException: Resource temporarily unavailable
	at org.newsclub.net.unix.NativeUnixSocket.accept(Native Method)
	at org.newsclub.net.unix.AFUNIXSocketImpl.accept(AFUNIXSocketImpl.java:64)
	at org.newsclub.net.unix.AFUNIXServerSocket.accept(AFUNIXServerSocket.java:106)
	at com.project.one.UnixSocketServer.run(UnixSocketServer.java:47)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by neuhaus** [comment]
i added a pull request for this issue, please have a look.

**Comment by kohlschuetter** [comment]
This should be fixed in 2.1.0. Please verify. Thanks for reporting!

**Comment by neuhaus** [comment]
Thanks!

**Comment by neuhaus** [comment]
FYI, I switched to netty for my UNIX socket java needs so I cannot validate this.
