### ISSUE TITLE
Error building project from source

### ISSUE THREAD

**Issue by ernanirst** [kohlschutter/junixsocket#37]
The project is not building from sources.

$> git clone https://github.com/kohlschutter/junixsocket.git
$> cd junixsocket
$> mvn package

Output:

[INFO] ------------------------------------------------------------------------
[INFO] Building junixsocket-demo 2.0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.kohlschutter.junixsocket:junixsocket-native-common:jar:2.0.5-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] junixsocket-parent ................................. SUCCESS [  0.893 s]
[INFO] junixsocket-common ................................. SUCCESS [  2.370 s]
[INFO] junixsocket-rmi .................................... SUCCESS [  1.107 s]
[INFO] junixsocket-mysql .................................. SUCCESS [  0.672 s]
[INFO] junixsocket-demo ................................... FAILURE [  0.009 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.140 s
[INFO] Finished at: 2017-03-09T19:40:11-03:00
[INFO] Final Memory: 37M/378M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project junixsocket-demo: Could not resolve dependencies for project com.kohlschutter.junixsocket:junixsocket-demo:jar:2.0.5-SNAPSHOT: Could not find artifact com.kohlschutter.junixsocket:junixsocket-native-common:jar:2.0.5-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :junixsocket-demo

**Comment by gesellix** [comment]
Did you try with the `with-native` profile? This should work:

```
mvn package -Pwith-native
```

See https://github.com/kohlschutter/junixsocket/blob/master/pom.xml#L65

**Comment by ernanirst** [comment]
Hello @gesellix, that also failed with same error. After a while I managed to get it working, basically, I had to go to junixsocket-native and junixsocket-native-common and run `mvn clean install`. Then, I could got to the parent directory and run `mvn clean package`.

Weird.
