### ISSUE TITLE
release version 2.0.5

### ISSUE THREAD

**Issue by dbyron0** [kohlschutter/junixsocket#38]
Not much has changed since 2.0.4, but it's been awhile and it sure would be nice to get log4j out of the classpath.  Any chance for a 2.0.5 in the near future?

Thanks much.

-DB

**Comment by dbyron0** [comment]
Ping?

**Comment by kohlschuetter** [comment]
This was fixed in 2.1.0, please verify. Thanks for reporting!

**Comment by kohlschuetter** [comment]
Please verify with 2.1.1

**Comment by dbyron0** [comment]
Yup, it's gone.  Thanks much.
