### ISSUE TITLE
Random segfaults caused by classloading

### ISSUE THREAD

**Issue by CodingFabian** [kohlschutter/junixsocket#41]
We more or less randomly see the following segfaults
```
Stack: [0x00007f626aa6b000,0x00007f626aaae000],  sp=0x00007f626aaac210,  free space=260k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x66fb16]  get_method_id(JNIEnv_*, _jclass*, char const*, char const*, bool, Thread*)+0x86
V  [libjvm.so+0x66ff92]  jni_GetMethodID+0xe2
C  [libjunixsocket-native-2.0.4625448555424496873.so+0x135d]  org_newsclub_net_unix_NativeUnixSocket_throwException+0x61
C  [libjunixsocket-native-2.0.4625448555424496873.so+0x1fd2]  Java_org_newsclub_net_unix_NativeUnixSocket_read+0x160
j  org.newsclub.net.unix.NativeUnixSocket.read(Ljava/io/FileDescriptor;[BII)I+0
j  org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXInputStream.read([BII)I+48
```

what happens here is that the native implementation wants to throw an AFUNIXSocketException. But somehow, it fails to load the class (FindClass returns null, and thus the native code crashes)

I assume the problem stems from the fact that AFUNIXSocketException is actually not referenced from the Java API and is probably not loaded by the JVM. Maybe the native code triggers an obscure JVM bug in that fact.

In my opinion all uses of AFUNIXSocketException in native code could be replaced by a plain IOException.

What do you guys think?

**Comment by CodingFabian** [comment]
There is also this:
https://svn.apache.org/repos/asf/mesos/branches/0.10.x/src/java/jni/convert.cpp

so apparently the native code uses the system classloader to locate the exception class, which in our case has no access to the Exception class.
Mesos worked around this the complicated way..

**Comment by kohlschuetter** [comment]
We're now throwing SocketExceptions directly, which should fix the issue.
Please verify on 2.1.0
Thanks for reporting!

**Comment by CodingFabian** [comment]
yes, this looks good. Checked from source.

Will try the new version soon, but as this is probably not going to reproduce anyway, I am closing this issue already now.
