### ISSUE TITLE
Read takes long time.

### ISSUE THREAD

**Issue by princrai** [kohlschutter/junixsocket#48]
Hello,

I am using JUnixSocket to read and write to a UNIX socket where a c++ process is listening to. I am seeing big difference between read and write cpu time. Read is taking good amount of long time(Attached the snapshot). Also wanted to check what should be the ideal buffer size to read from the socket. Write now I am reading in a while loop of size 224K. 

Thanks,
Prince
![junixread](https://user-images.githubusercontent.com/12469909/40450134-944d294a-5e8f-11e8-8a0d-7e4d1d961739.png)

**Comment by kohlschuetter** [comment]
Please provide a reproducible test case as well as a description of the environment you're seeing this issue in (platform, architecture, etc.)
