### ISSUE TITLE
Update/Fix Dependency Documentation Page (2.1.2)

### ISSUE THREAD

**Issue by mina-asham** [kohlschutter/junixsocket#57]
The dependency documentation page: https://kohlschutter.github.io/junixsocket/dependency.html says that to use the library you need to include **junixsocket-core** as a dependency.

This artifact does NOT contain the required Java classes anymore, they moved to junixsocket-common, I needed junixsocket-common and junixsocket-native-common for it to work.

The documentation needs updating with that. It also feels weird that I have to add two dependencies in my pom file, can the core package work again?

**Comment by kohlschuetter** [comment]
Thanks for reporting! I've added the missing dependency to junixsocket-common, so all necessary artifacts should now be retrieved when you add "junixsocket-core" as the dependency. Please verify.

**Comment by mina-asham** [comment]
Thanks for fixing it so quick, I will test it when next version is released to maven.

**Comment by runekaagaard** [comment]
Thanks for this, its still an issue.

**Comment by kohlschuetter** [comment]
Please upgrade your dependencies to junixsocket 2.2.0 and try again

**Comment by runekaagaard** [comment]
Yes, it works now. Thx!!
