### ISSUE TITLE
x86_64-MacOSX-gpp not in junixsocket-native-common-2.1.2

### ISSUE THREAD

**Issue by gesellix** [kohlschutter/junixsocket#59]
Since junixsocket-native-common:2.1.2 the previously provided `lib/x86_64-MacOSX-gpp/jni/libjunixsocket-native-<version>.jnilib/.dylib` library isn't contained anymore.

The error message looks like this:

```
java.lang.UnsatisfiedLinkError: Artifact junixsocket-native-common does not contain library for x86_64-MacOSX
```

Can you create another release including both platforms x86_64-MacOSX-gpp and amd64-Linux-gpp?

**Comment by kohlschuetter** [comment]
Please upgrade your dependencies to junixsocket 2.2.0; this should be fixed now.

**Comment by gesellix** [comment]
@kohlschuetter thanks a lot for the quick fix, I can confirm that it works on Mac OS X again.
