### ISSUE TITLE
java8 target

### ISSUE THREAD

**Issue by KostyaSha** [kohlschutter/junixsocket#65]
```
INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (display-info) @ yet-another-docker-plugin ---
[INFO] Restricted to JDK 1.8 yet com.github.kostyasha.yet-another-docker:yet-another-docker-java:jar:0.1.0-SNAPSHOT:compile contains META-INF/versions/9/org/newsclub/net/unix/NativeLibraryLoader$StandardLibraryCandidate.class targeted to 53.0
[INFO] Ignoring requireUpperBoundDeps in com.google.guava:guava
[WARNING] Rule 2: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:
Found Banned Dependency: com.github.kostyasha.yet-another-docker:yet-another-docker-java:jar:0.1.0-SNAPSHOT
Use 'mvn dependency:tree' to locate the source of the banned dependencies.
```
If i correctly understand issue in:
```
compile contains META-INF/versions/9/org/newsclub/net/unix/NativeLibraryLoader$StandardLibraryCandidate.class targeted to 53.0
```
Is it possible to recompile with java8 so bytecode requirement will be lower?

**Comment by sriemer** [comment]
Please provide full logs/commands and information about your target system.

You might want to look at the custom hack I’ve developed for s390x native compile.
See #62

Note: The tests don’t work with Java 8 compile. So the demo app should be used for testing. `clang` is required. The only platform for native compile seems to be macOS besides my custom s390x hacks. For everything else, clang cross compile is used.

**Comment by KostyaSha** [comment]
Message mean that target classes compiled with java 9, i have projects based on java8 so can't use them. For compatibility it is possible to use maven plugin settings https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html

**Comment by kohlschuetter** [comment]
It looks like your error message is a red herring.

The jar itself provides the correct Java 8 version of the class.
Classes under "META-INF/versions/9" will always be Java 9 classes.

Just make sure you that you use Java 9 or later when you build the junixsocket package.

**Comment by KostyaSha** [comment]
I'm not building this project sources, i have a project that uses maven-enforcer-plugin that probably doesn't know about Multi-Release jars...

**Comment by ryanthon** [comment]
@KostyaSha Did you ever figure this out? My project is built using Java 8, but crashes at Runtime because the jar that Maven pulls only has Java 9 class versions.
