### ISSUE TITLE
java.net.SocketException: Protocol wrong type for socket

### ISSUE THREAD

**Issue by adamtg** [kohlschutter/junixsocket#66]
I just discovered this library today.  i am using version 2.2.0.  This is my code snippet:
```
       File socketFile = new File("/dev/log");
    	
    	try (AFUNIXSocket sock = AFUNIXSocket.newInstance()) {
    	      try {
    	        sock.connect(new AFUNIXSocketAddress(socketFile));
    	      } catch (IOException e) {
    	        throw e;
    	      }
...
```

and i am getting this error:

```
java.net.SocketException: Protocol wrong type for socket
	at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
	at org.newsclub.net.unix.AFUNIXSocketImpl.connect(AFUNIXSocketImpl.java:251)
	at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:144)
	at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:123)
...
```
Is there any additional configuration i need to do, or is there something else i am doing wrong?

thank you

**Comment by sriemer** [comment]
In /dev only root may use special (device) files. Use a different directory like e.g. /tmp.
See demo app simple test client for a working example: https://github.com/kohlschutter/junixsocket/blob/master/junixsocket-demo/src/main/java/org/newsclub/net/unix/demo/SimpleTestClient.java

**Comment by adamtg** [comment]
So it is a permission problem, not a socket creation error.  thank you.
