### ISSUE TITLE
Is junixsocket supported on ppc64le

### ISSUE THREAD

**Issue by rashmi-sakhalkar** [kohlschutter/junixsocket#67]
In my project repo I am using docker gradle plugin.
During dockerize i get an error complaining for architecture.

java.lang.ExceptionInInitializerError
	at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:36)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:54)
	at com.github.dockerjava.jaxrs.ApacheUnixSocket.<init>(ApacheUnixSocket.java:51)

Caused by: java.lang.RuntimeException: Unhandled architecture/OS: ppc64le-Linux
	at org.newsclub.net.unix.NarSystem.getAOLs(NarSystem.java:110)

Is junixsocket supported on ppc64le ?

**Comment by sriemer** [comment]
Nope, not yet.
See: https://github.com/kohlschutter/junixsocket/blob/master/junixsocket-native/src/main/nar/aol.properties
Feel free to add the llvm/clang cross compilation for it. As this is little endian, it should work as expected and you should not have as much hassle as we had with s390x in #62 .

**Comment by rashmi-sakhalkar** [comment]
Thanks for the quick reply. I have started working on code changes for the same.

**Comment by rashmi-sakhalkar** [comment]
Hi,

I could build the junixsocket-native successfully as per below logs.

junixsocket-native <<<
[INFO]
[INFO]
[INFO] --- spotbugs-maven-plugin:3.1.10:check (spotbugs-during-install) @ junixsocket-native ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.744 s
[INFO] Finished at: 2019-08-06T05:01:48Z
[INFO] ------------------------------------------------------------------------
root@80ea80478ad9:/junixsocket/junixsocket-native#
root@80ea80478ad9:/junixsocket/junixsocket-native# cd ..



root@80ea80478ad9:/junixsocket# junixsocket-native-prebuilt/bin/list-available-in-m2repo.sh -c 2.2.1-SNAPSHOT
ppc64le-Linux-clang-jni
root@80ea80478ad9:/junixsocket#


I tried to perform the below step but build fails with below test failures.
cd junixsocket
mvn clean install -Djunixsocket.custom.arch=ppc64le-Linux-clang-jni -Dmaven.javadoc.skip=true


ERROR:-
Attached failure log file..

If I skip tests and run the build its a success.
mvn clean install -Djunixsocket.custom.arch=ppc64le-Linux-clang-jni -Dmaven.javadoc.skip=true -Dpmd.skip=true -Dmaven.test.skip=true

[TestFailureLogs.txt](https://github.com/kohlschutter/junixsocket/files/3470537/TestFailureLogs.txt)

Can you pls provide pointers to tackle the test failure.

**Comment by rashmi-sakhalkar** [comment]
For the above test failure issue I edited the test file junixsocket/junixsocket-common/src/test/java/org/newsclub/net/unix/AcceptTimeoutTest.java

and update line no:69 
from  final int timeoutMillis = 250;
to  final int timeoutMillis = 252;

and then the build was success.

**Comment by sriemer** [comment]
Thanks, so you basically just ran into #63 and used the same fix as I do in PR #64.
Would you mind sharing your code? TIA

**Comment by rashmi-sakhalkar** [comment]
![aol_properties_Power](https://user-images.githubusercontent.com/20107581/62517331-d60d6600-b844-11e9-9dc0-f5d5d6113fca.png)

As shown in above screenshot I set the properties in aol.properties file.

**Comment by rashmi-sakhalkar** [comment]
Just to mention during the mvn build of junixsocket-native project I had to do the below change in pom.xml . 

<plugins>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <configuration>
              <c>
                <toolPath>${junixsocket.native.default.toolPath}</toolPath>
              </c>
              <linker>
                <prefix>${junixsocket.native.default.toolPath}</prefix>
                <toolPath></toolPath>
                
                <name>clang</name>
              </linker>
            </configuration>
          </plugin>
        </plugins>

The <name> tag value wasn't being obtained so I had to explicitly set it.

**Comment by rashmi-sakhalkar** [comment]
I am trying to build the cross compilation steps. 

Facing the below error.
[INFO] junixsocket-parent ................................. SUCCESS [  6.796 s]
[INFO] junixsocket-native-cross ........................... FAILURE [ 21.671 s]
[INFO] junixsocket-native ................................. SKIPPED
[INFO] junixsocket-native-common .......................... SKIPPED
[INFO] junixsocket-native-custom .......................... SKIPPED
[INFO] junixsocket-common ................................. SKIPPED
[INFO] junixsocket-server ................................. SKIPPED
[INFO] junixsocket-rmi .................................... SKIPPED
[INFO] junixsocket-mysql .................................. SKIPPED
[INFO] junixsocket-core ................................... SKIPPED
[INFO] junixsocket-demo ................................... SKIPPED
[INFO] junixsocket-dist ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.492 s
[INFO] Finished at: 2019-08-07T04:48:09Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:3.0.0-M1:install-file (install-powerpc64le-Linux-clang) on project junixsocket-native-cross: The specified file '/junixsocket/junixsocket-native-cross/target/junixsocket-native-powerpc64le-Linux-clang-llvm/junixsocket-native-2.2.1-SNAPSHOT-powerpc64le-Linux-clang-jni.nar' not exists -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :junixsocket-native-cross
root@80ea80478ad9:/junixsocket#

Build command used:-
mvn clean install -Dcross=true -Dmaven.javadoc.skip=true

**Comment by sriemer** [comment]
I've checked the llvm source at `lld/ELF/Driver.cpp`.
For the `elf64lppc` emulation, at least **llvm 7 is required**.

See: https://github.com/llvm/llvm-project/blob/llvmorg-7.0.1/lld/ELF/Driver.cpp#L132

**Comment by sriemer** [comment]
I've prepared the ppc64le build now:
https://github.com/sriemer/junixsocket/commits/ppc64le
See the long commit descriptions of the four patches for details. Works for me. amd64 Linux is compiled native and cross, ppc64le is compiled cross.
Hope this helps.

**Comment by sriemer** [comment]
@rashmi-sakhalkar Can you please test the code from there? TIA

**Comment by sriemer** [comment]
Works for me. See PR #68 .

**Comment by rashmi-sakhalkar** [comment]
@sriemer 

I faced the below issue for target sdk.

Fix: Set SDK target as powerpc64le-linux-gnu in pom.xml

Error:
[INFO] --- nar-maven-plugin:3.6.0:nar-compile (default-nar-compile) @ junixsocket-native ---
[INFO] Compiling 1 native files
[INFO] 1 total files to be compiled.
[INFO] Found 4 processors available
[INFO] Limited used processors to 1
[INFO]
Starting Core 0 with 1 source files...
[ERROR] Could not find SDK root for target: ppc64le-linux-gnu
[ERROR] Available targets:
[ERROR] - powerpc64le-linux-gnu
[ERROR] - current (use current target)
[ERROR] - default (use default clang)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.888 s
[INFO] Finished at: 2019-08-08T09:13:17Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.6.0:nar-compile (default-nar-compile) on project junixsocket-native: NAR: Compile failed: /junixsocket/junixsocket-native/crossclang/bin/clang failed with return code 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by sriemer** [comment]
Thanks for the hint! I've amended the code in the commit and the commit description accordingly and the PR is updated now.

**Comment by rashmi-sakhalkar** [comment]
Can you please let me know if your PR is merged or by when it would be merged.

**Comment by sriemer** [comment]
@rashmi-sakhalkar will do but can’t tell when @kohlschuetter will have the next review time slot available.

**Comment by rashmi-sakhalkar** [comment]
Thanks .

**Comment by madscientist159** [comment]
Any progress on getting this merged?  Kind of a nuisance to have to fork / patch / redirect repos to get Zimbra to build. :wink:

**Comment by rashmi-ibm** [comment]
@sriemer @kohlschuetter  It would be good to have this issue related PR merged sooner. Any update on the PR merger timeline.

Thanks ...

**Comment by sriemer** [comment]
I'm not a maintainer here. Depends on @kohlschuetter.

**Comment by kohlschuetter** [comment]
Please verify on junixsocket 2.3.0. Thanks!

**Comment by rashmi-ibm** [comment]
I tried to validate the jar but got below response

# java -jar junixsocket-selftest-2.3.0-jar-with-dependencies.jar
junixsocket selftest

This program determines whether junixsocket is supported on the current platform.
The final line should say whether the selftest passed or failed.
If the selftest failed, please visit https://github.com/kohlschutter/junixsocket/issues
and file a new bug report with the output below.

selftest version 2.3.0

System properties:

awt.toolkit: sun.awt.X11.XToolkit
file.encoding: UTF-8
file.separator: /
java.awt.graphicsenv: sun.awt.X11GraphicsEnvironment
java.awt.printerjob: sun.print.PSPrinterJob
java.class.path: junixsocket-selftest-2.3.0-jar-with-dependencies.jar
java.class.version: 55.0
java.home: /usr/lib/jvm/java-11-openjdk-11.0.4.11-1.el7_7.ppc64le
java.io.tmpdir: /tmp
java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
java.runtime.name: OpenJDK Runtime Environment
java.runtime.version: 11.0.4+11-LTS
java.specification.name: Java Platform API Specification
java.specification.vendor: Oracle Corporation
java.specification.version: 11
java.vendor: Oracle Corporation
java.vendor.url: http://java.oracle.com/
java.vendor.url.bug: http://bugreport.java.com/bugreport/
java.vendor.version: 18.9
java.version: 11.0.4
java.version.date: 2019-07-16
java.vm.compressedOopsMode: Zero based
java.vm.info: mixed mode
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.specification.name: Java Virtual Machine Specification
java.vm.specification.vendor: Oracle Corporation
java.vm.specification.version: 11
java.vm.vendor: Oracle Corporation
java.vm.version: 11.0.4+11-LTS
jdk.debug: release
line.separator: \n
os.arch: ppc64le
os.name: Linux
os.version: 3.10.0-1062.4.1.el7.ppc64le
path.separator: :
sun.arch.data.model: 64
sun.boot.library.path: /usr/lib/jvm/java-11-openjdk-11.0.4.11-1.el7_7.ppc64le/lib
sun.cpu.endian: little
sun.cpu.isalist:
sun.io.unicode.encoding: UnicodeLittle
sun.java.command: junixsocket-selftest-2.3.0-jar-with-dependencies.jar
sun.java.launcher: SUN_STANDARD
sun.jnu.encoding: UTF-8
sun.management.compiler: HotSpot 64-Bit Tiered Compilers
sun.os.patch.level: unknown
user.country: US
user.dir: /rash/junixsocket
user.home: /root
user.language: en
user.name: root
user.timezone:

AFUNIXSocket.isSupported: true

Testing "junixsocket-common"...
.
'-- JUnit Jupiter [OK]
  +-- AcceptTimeoutTest [OK]
  | +-- testCatchTimeout() [X] Timeout not properly honored. Exception thrown after 495ms vs. expected 500ms ==> expected: <true> but was: <false>
  | '-- testTimeoutAfterDelay() [OK]
  +-- AFUNIXSocketAddressTest [OK]
  | '-- testPort() [OK]
  +-- AvailableTest [OK]
  | +-- testAvailableAtClient() [OK]
  | '-- testAvailableAtServer() [OK]
  +-- BufferOverflowTest [OK]
  | +-- writeOverflow() [OK]
  | +-- readUpTo() [OK]
  | '-- readOutOfBounds() [OK]
  +-- CancelAcceptTest [OK]
  | '-- issue6test1() [OK]
  +-- EndOfFileJavaTest [OK]
  | +-- clientWriteToSocketClosedByClient() [OK]
  | +-- clientWriteToSocketClosedByServer() [OK]
  | +-- bidirectionalSanity() [OK]
  | +-- serverWriteToSocketClosedByClient() [OK]
  | +-- serverWriteToSocketClosedByServer() [OK]
  | +-- clientReadEof() [OK]
  | '-- serverReadEof() [OK]
  +-- EndOfFileTest [OK]
  | +-- clientWriteToSocketClosedByClient() [OK]
  | +-- clientWriteToSocketClosedByServer() [OK]
  | +-- bidirectionalSanity() [OK]
  | +-- serverWriteToSocketClosedByClient() [OK]
  | +-- serverWriteToSocketClosedByServer() [OK]
  | +-- clientReadEof() [OK]
  | '-- serverReadEof() [OK]
  +-- FileDescriptorsTest [OK]
  | +-- testNoAncillaryReceiveBuffer() [OK]
  | +-- testSendRecvFileDescriptors() [OK]
  | +-- testBadFileDescriptor() [OK]
  | +-- testAncillaryReceiveBufferTooSmall() [OK]
  | +-- testFileInputStreamPartiallyConsumed() [OK]
  | '-- testFileInputStream() [OK]
  +-- PeerCredentialsTest [OK]
  | '-- testSameProcess() [OK]
  +-- ServerSocketCloseTest [OK]
  | +-- testUnblockAcceptsWithSoTimeout() [OK]
  | '-- testUnblockAcceptsWithoutSoTimeout() [OK]
  +-- SoTimeoutTest [OK]
  | +-- issue14Fail() [OK]
  | '-- issue14Pass() [OK]
  '-- TcpNoDelayTest [OK]
    +-- testDefaultImpl() [OK]
    '-- testStrictImpl() [OK]

Failures (1):
  JUnit Jupiter:AcceptTimeoutTest:testCatchTimeout()
    MethodSource [className = 'org.newsclub.net.unix.AcceptTimeoutTest', methodName = 'testCatchTimeout', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: Timeout not properly honored. Exception thrown after 495ms vs. expected 500ms ==> expected: <true> but was: <false>
       org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
       org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
       org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:193)
       org.newsclub.net.unix.AcceptTimeoutTest.lambda$testCatchTimeout$0(AcceptTimeoutTest.java:61)
       org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$2(AssertTimeout.java:98)
       org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$4(AssertTimeout.java:132)
       java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
       java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       java.base/java.lang.Thread.run(Thread.java:834)

Test run finished after 3784 ms
[        13 containers found      ]
[         0 containers skipped    ]
[        13 containers started    ]
[         0 containers aborted    ]
[        13 containers successful ]
[         0 containers failed     ]
[        36 tests found           ]
[         0 tests skipped         ]
[        36 tests started         ]
[         0 tests aborted         ]
[        35 tests successful      ]
[         1 tests failed          ]

Testing "junixsocket-rmi"...
.
'-- JUnit Jupiter [OK]
  '-- RemoteFileDescriptorTest [OK]
    +-- testReadWrite() [OK]
    +-- testFindSocketFactory() [OK]
    +-- testRemoteStdout() [OK]
    +-- testWriteAndReadHello() [OK]
    '-- testServiceProxy() [OK]

Test run finished after 219 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         5 tests found           ]
[         0 tests skipped         ]
[         5 tests started         ]
[         0 tests aborted         ]
[         5 tests successful      ]
[         0 tests failed          ]


Selftest results:
FAIL    junixsocket-common      35/36
PASS    junixsocket-rmi 5/5

Supported capabilities:   [CAPABILITY_PEER_CREDENTIALS, CAPABILITY_ANCILLARY_MESSAGES, CAPABILITY_FILE_DESCRIPTORS, CAPABILITY_ABSTRACT_NAMESPACE]
Unsupported capabilities: []

Selftest FAILED
[root@p006vm32 junixsocket]#

**Comment by sriemer** [comment]
I see, it is the AcceptTimeoutTest once again. Basically it should check for +/- 5 ms or +/- 10 ms as the Linux kernel has freedom to schedule tasks according to priority. Not every system has a realtime scheduler. First reported in #63.
