### ISSUE TITLE
java: symbol lookup error: /tmp/libtmp8709324396123266813libjunixsocket-native-2.2.0.so: undefined symbol: stat

### ISSUE THREAD

**Issue by 137268431** [kohlschutter/junixsocket#69]
java: symbol lookup error: /tmp/libtmp8709324396123266813libjunixsocket-native-2.2.0.so: undefined symbol: stat  

What's the problem? thank you

**Comment by sriemer** [comment]
That usually occurs if trying to load a library for a wrong CPU architecture. What exactly are you trying to do/support with self-compilation?

**Comment by sriemer** [comment]
@137268431 You didn't answer my question. Please close this if this is resolved.

**Comment by kohlschuetter** [comment]
Please try again with the latest release. If that doesn't work, please specify your system environment (operating system, architecture, libc)

**Comment by kohlschuetter** [comment]
Please re-test with junixsocket 2.3.0; there were some changes that may have fixed your issue.

**Comment by QuChen88** [comment]
I was able to reproduce this same error on my local machine. using version 2.2.0. I am using OpenJDK 1.8, Linux 4.9.217, X86_64. 

I haven't tried to use the newest version 2.3.1 yet. But I was able to narrow down the exact line of code that caused this error to occur in 2.2.0. It happened for me in AFUNIXServerSocket.bind(). Hope this helps.

**Comment by QuChen88** [comment]
Opened another issue to track this https://github.com/kohlschutter/junixsocket/issues/81
