### ISSUE TITLE
Junixsocket doesn't work on Java 13

### ISSUE THREAD

**Issue by timboven** [kohlschutter/junixsocket#70]
Java 13 changed internally the Socket implementations, due to these changes this codebase doesn't work correctly on Java 13 anymore.
An example of this is e.g. the bug reported here: https://github.com/docker-java/docker-java/issues/1245
That bug is however caused by this codebase and not by docker-java itself.

The setCreated()-method isn't their anymore in this new implementation.

**Comment by rraptorr** [comment]
I've fixed it in #71, at least client side ;)

**Comment by kohlschuetter** [comment]
junixsocket 2.2.1 is now staged at https://oss.sonatype.org/content/groups/staging

Please temporarily add this repository to your configuration and see if it works.
Thanks!

**Comment by kohlschuetter** [comment]
junixsocket 2.2.1 (with support for Java 13) has been released, closing.
