### ISSUE TITLE
Is JavaHttpServer supported over JUnixSocket?

### ISSUE THREAD

**Issue by rajulm** [kohlschutter/junixsocket#72]
Thanks for writing this code and making our lives a lot easier.

My use case is to have http over unix sockets to serve requests like as below:
```
curl --unix-socket /var/run/docker.sock http://localhost/images/json
```

Is it possible to have a Java http server over JunixSockets out of the box? Or do I need to write the server code on my own? I tried hooking this code up somehow in the HttpServer code that we have but unfortunately it doesn't support the JUnixSockets out of the box.

**Comment by kohlschuetter** [comment]
Hi rajulm,
I added support in commit 25b8340692ed1f67704c9c9ed16b9e39d1d5a9b2.
Please verify it works for you!

**Comment by kohlschuetter** [comment]
Please verify on junixsocket 2.3.0, which was released today. Thanks!
