### ISSUE TITLE
Does it work with X server?

### ISSUE THREAD

**Issue by ansorre** [kohlschutter/junixsocket#74]
Just a question: has anyone ever tried to use this to connect to a local xorg server?
I'm trying to do exactly that and it connects and everything seems fine. Anyway, unfortunately, reading the input stream seems not to work.

   File socketFile = new File("/tmp/.X11-unix/X0");
   AFUNIXSocket sock = AFUNIXSocket.newInstance();
   sock.connect(new AFUNIXSocketAddress(socketFile));

   InputStream in=sock.getInputStream();
   in.available (); // this always returns 0, even if I'm sure there are events to be read.

   Any suggestion?

Thanks

**Comment by Antonio-Sorrentini** [comment]
Yes it works! Sorry, it was me not knowing a couple of thing of X protocol. X sends events only after you register to get them. ;)
