### ISSUE TITLE
NullPointerException in NativeLibraryLoader

### ISSUE THREAD

**Issue by darinhoward** [kohlschutter/junixsocket#77]
NativeLibraryLoader will fail when `getClass().getClassLoader()` returns null; which is possible when running in the bootstrap class loader. (https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getClassLoader()) 

```
  public synchronized void loadLibrary() {
    synchronized (getClass().getClassLoader()) { // NOPMD We want to lock this class' classloader.
```

**Comment by kohlschuetter** [comment]
Fixed in 2.3.2; please verify.
