### ISSUE TITLE
UnsatisfiedLinkError: Artifact junixsocket-native-custom does not contain library for amd64-Linux

### ISSUE THREAD

**Issue by kuldeep992** [kohlschutter/junixsocket#82]
`java.lang.UnsatisfiedLinkError: Artifact junixsocket-native-custom does not contain library for amd64-Linux
	at org.newsclub.net.unix.NativeLibraryLoader.findLibraryArtifact(NativeLibraryLoader.java:70)
	at org.newsclub.net.unix.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:127)
	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:37)
	at org.newsclub.net.unix.AFUNIXServerSocket.<init>(AFUNIXServerSocket.java:56)
	at org.newsclub.net.unix.AFUNIXServerSocket.newInstance(AFUNIXServerSocket.java:69)`

I faced an issue with junixsocket lib 2.3.2, related to symbol lookup error: undefined symbol: stat. I commented the details on this ticket: https://github.com/kohlschutter/junixsocket/issues/81

As a workaround, I replaced 2.3.2 with older version i.e. 2.1.0. I choose this specific version because in 2.2.0 the above issue got introduced. 

It there something we can do to have a workaround to keep things moving on our end?

Environment details: 
Host: Docker container of base CentOS-6 image. (docker pull centos:6)
Architecture: x86_64

**Comment by maccuaa** [comment]
Ran into the same issue when this library was invoked via the [gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) (through [docker-java](https://github.com/docker-java/docker-java)).

docker-java: 3.25
gradle-docker-plugin: 5.0.0
OS: RHEL 8.1

Note that the same code has no issue running on Mac OS Mojave or CentOS 7.

**Comment by kohlschuetter** [comment]
This is the same issue as #81.
See #81 for a workaround that you can apply on these old Linux distributions.
