### ISSUE TITLE
Missing error checks in the native code

### ISSUE THREAD

**Issue by DemiMarie** [kohlschutter/junixsocket#83]
The native code does not check the return value of several JNI functions which can fail.

**Comment by kohlschuetter** [comment]
Please provide a pull request with some proposed fixes. Thanks!

**Comment by DemiMarie** [comment]
I will at some point, when I have free time.

This will most likely involve refactoring the native code so that resources are acquired in `JNI_OnLoad` and released in `JNI_OnUnload`.
