### ISSUE TITLE
Is there a list of exception that can happen when using this library?

### ISSUE THREAD

**Issue by criticalx7** [kohlschutter/junixsocket#87]
Can author point me to the list of all runtime exceptions that can happen when using this (ex. IOException). In other word, what error must i be aware of when sending message to junixsocket.

**Comment by kohlschuetter** [comment]
Hello there!

I'm not sure I fully understand the extent of your question, but all checked exceptions are marked as such.
Occasionally, unchecked exceptions such as IllegalStateException and IllegalArgumentException can be thrown when given illegal input or state.

What are you trying to solve?

**Comment by criticalx7** [comment]
Nothing serious. I'm trying to document and replicate all possible failures and errors that happen from using this library. This is one of the part for developing resilience of our app.

**Comment by kohlschuetter** [comment]
Got it. I hope my above answer helps!
