### ISSUE TITLE
junixsocket-core JAR missing from Maven Central

### ISSUE THREAD

**Issue by itoijala-huld** [kohlschutter/junixsocket#93]
Something appears to have gone wrong with the upload of junixsocket-core to maven Central.
Maven only has the POM but not any JARs.

See https://repo1.maven.org/maven2/com/kohlschutter/junixsocket/junixsocket-core/2.4.0/

For comparison, here is 2.3.4: https://repo1.maven.org/maven2/com/kohlschutter/junixsocket/junixsocket-core/2.3.4/

This might also affect some other components, I didn't check exhaustively.

**Comment by kohlschuetter** [comment]
Thanks for reporting! Beginning with 2.4.0, junixsocket-core is now a POM-only artifact.

You have to specify the dependency like this:

```
<dependency>
  <groupId>com.kohlschutter.junixsocket</groupId>
  <artifactId>junixsocket-core</artifactId>
  <version>2.4.0</version>
  <type>pom</type>
</dependency>
```

Since this obviously was not clearly communicated, I've now added some more clear instructions (9c0145e).

**Comment by kohlschuetter** [comment]
@itoijala-huld Please verify if adding the "type" fixes the issue for you.

**Comment by itoijala-huld** [comment]
Thanks, that does fix the issue.

I'm using Gradle, so I followed the instructions at https://stackoverflow.com/a/55579207.
